<?php get_header('single');?>
            	
	<div id="main" class="" style="overflow:hidden !important;">
		<div class="avada-row" style="">
		<div id="content" style="width:100%">
				<div id="post-785" class="post-785 page type-page status-publish hentry">
						<div class="post-content">

				<!-- START REVOLUTION SLIDER 2.3.91 -->
				
								
								<div id="rev_slider_3_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" style="margin:0px auto;background-color:#E9E9E9;padding:0px;margin-top:0px;margin-bottom:0px;max-height:220px;">
					<div id="rev_slider_3_1" class="rev_slider fullwidthabanner" style="display:none;max-height:220px;height:220;">						
										<ul>
								<li data-transition="random" data-slotamount="7" >
						<img src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/10/sbprev3.png"  alt="sbprev3 SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" />
											</li>
									<li data-transition="random" data-slotamount="7" >
						<img src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/10/sbprev1.png"  alt="sbprev1 SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" />
											</li>
									<li data-transition="random" data-slotamount="7" >
						<img src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/10/sbprev2.png"  alt="sbprev2 SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" />
											</li>
								</ul>
														</div>
				</div>				
							
			<script type="text/javascript">

				var tpj=jQuery;
				
									tpj.noConflict();
								
				var revapi3;
				
				tpj(document).ready(function() {
				
				if (tpj.fn.cssOriginal != undefined)
					tpj.fn.css = tpj.fn.cssOriginal;
				
				if(tpj('#rev_slider_3_1').revolution == undefined)
					revslider_showDoubleJqueryError('#rev_slider_3_1');
				else
				   revapi3 = tpj('#rev_slider_3_1').show().revolution(
					{
						delay:9000,
						startwidth:960,
						startheight:220,
						hideThumbs:0,
						
						thumbWidth:100,
						thumbHeight:50,
						thumbAmount:3,
						
						navigationType:"bullet",
						navigationArrows:"solo",
						navigationStyle:"square-old",
						
						touchenabled:"on",
						onHoverStop:"on",
						
						navigationHAlign:"center",
						navigationVAlign:"bottom",
						navigationHOffset:0,
						navigationVOffset:20,

						soloArrowLeftHalign:"left",
						soloArrowLeftValign:"center",
						soloArrowLeftHOffset:20,
						soloArrowLeftVOffset:0,

						soloArrowRightHalign:"right",
						soloArrowRightValign:"center",
						soloArrowRightHOffset:20,
						soloArrowRightVOffset:0,
								
						shadow:3,
						fullWidth:"on",

						stopLoop:"off",
						stopAfterLoops:-1,
						stopAtSlide:-1,

						shuffle:"off",
						
						hideSliderAtLimit:0,
						hideCaptionAtLimit:0,
						hideAllCaptionAtLilmit:0,
						startWithSlide:0	
					});
				
				});	//ready
				
			</script>
			
							<!-- END REVOLUTION SLIDER -->

				<div class="demo-sep sep-none" style="margin-top:60px;"></div>
<style type='text/css'>
	#tabs-1,#tabs-1.tabs-vertical .tabs,#tabs-1.tabs-vertical .tab_content{border-color:#ebeaea !important;}
	
        #main #tabs-1.tabs-horizontal,#tabs-1.tabs-vertical .tab_content,.pyre_tabs .tabs-container{background-color:#ffffff;}
        /*#main #tabs-1.tabs-horizontal,#tabs-1.tabs-vertical .tab_content,.pyre_tabs .tabs-container{background-color:#ffffff !important;}*/

	body.dark #tabs-1.shortcode-tabs .tab-hold .tabs li,body.dark #sidebar .tab-hold .tabs li{border-right:1px solid #ffffff !important;}
	body.dark #tabs-1.shortcode-tabs .tab-hold .tabs li:last-child{border-right:0 !important;}
	body.dark #main #tabs-1 .tab-hold .tabs li a{background:#ebeaea !important;border-bottom:0 !important;color:#747474 !important;}
	body.dark #main #tabs-1 .tab-hold .tabs li a:hover{background:#ffffff !important;border-bottom:0 !important;}
	body #main #tabs-1 .tab-hold .tabs li.active a,body #main #tabs-1 .tab-hold .tabs li.active{background:#ffffff !important;border-bottom:0 !important;}
	#sidebar .tab-hold .tabs li.active a{border-top-color:#53aedb !important;}
	</style><div id="tabs-1" class="tab-holder shortcode-tabs clearfix tabs-horizontal"><div class="tab-hold tabs-wrapper"><ul id="tabs" class="tabset tabs"><li><a href="#tab1">QUEM SOMOS</a></li><li><a href="#tab2">NOSSA HISTÓRIA</a></li><li><a href="#tab3">ESTRUTURA DE GOVERNANÇA</a></li><li><a href="#tab4">NOSSA EQUIPE</a></li><li><a href="#tab5">DOCUMENTOS INSTITUCIONAIS</a></li></ul><div class="tab-box tabs-container">
<div id="tab1" class="tab tab_content">
<img alt="seta azul SEBRAE PREVIDÊNCIA" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/seta-azul.png" width="22" height="44" title="SEBRAE PREVIDÊNCIA" /> <div class="title"><h2>Quem Somos</h2><div class="title-sep-container"><div class="title-sep"></div></div></div>
<p>O SEBRAE PREVIDÊNCIA - Instituto Sebrae de Seguridade Social é uma Entidade Fechada de Previdência Complementar. A Portaria nº 16, de 2 de fevereiro de 2004, aprovou a sua constituição e autorizou o seu funcionamento, tendo como base o inciso I do art. 33, combinado com o art. 74, ambos da Lei Complementar nº 109, e inciso IV do art. 11 do Decreto nº 4.818, de 26 de agosto de 2003.</p>
<p>Nosso Instituto é constituído sob a forma de sociedade civil, sem fins lucrativos, de personalidade jurídica de direito privado, criado pelo Serviço Brasileiro de Apoio às Micro e Pequenas Empresas &#8211; SEBRAE.</p>
<p>As Unidades que compõem o Sistema Sebrae e a ABASE &#8211; Associação Brasileira dos Sebrae Estaduais, mediante a celebração dos respectivos Convênios de Adesão, são Patrocinadoras do Plano SEBRAEPREV, além do próprio SEBRAE PREVIDÊNCIA.</p>
<p>As atividades foram iniciadas com o objetivo de complementar os benefícios concedidos pela previdência social mediante administração do Plano SEBRAEPREV.</p>
<p>As entidades fechadas de previdência complementar, como o SEBRAE PREVIDÊNCIA, são regulamentadas pelo Conselho de Gestão da Previdência Complementar &#8211; CGPC e fiscalizadas pela Superintendência Nacional de Previdência Complementar – PREVIC. Esses dois órgãos são vinculados ao Ministério da Previdência Social.</p>
<p><strong style="color: #4a7ebb;">Missão</strong><img class="alignright" style="float: right !important; margin: 0 0 15px 0;" alt="missao sebraeprev1 SEBRAE PREVIDÊNCIA" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/missao_sebraeprev1.png" width="244" height="251" title="SEBRAE PREVIDÊNCIA" /></p>
<p style="clear: none !important;">“Contribuir para a melhor qualidade de vida de seus participantes, oferecendo produtos e serviços previdenciários adequados às suas necessidades e de elevado padrão de excelência, com atuação transparente e socialmente responsável, alinhada às expectativas de seus patrocinadores.”.</p>
<p style="clear: none !important;"><span style="color: #4a7ebb;"><strong>Visão</strong></span></p>
<p style="clear: none !important;">“Ser referência no mercado de previdência complementar primando pela excelência de resultados na gestão de produtos previdenciários para seus Participantes, Patrocinadores e Instituidores”</p>
<p style="clear: none !important;"><span style="color: #4a7ebb;"><strong>Valores Corporativos</strong></span></p>
<ul>
<li>Princípios Éticos</li>
<li>Equidade</li>
<li>Transparência</li>
<li>Responsabilidade</li>
<li>Justiça</li>
<li>Imparcialidade</li>
<li>Discrição</li>
<li>Confidencialidade</li>
</ul>
</div>
<div id="tab2" class="tab tab_content">
<img alt="seta azul SEBRAE PREVIDÊNCIA" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/seta-azul.png" width="22" height="44" title="SEBRAE PREVIDÊNCIA" /> <div class="title"><h2>Nossa História</h2><div class="title-sep-container"><div class="title-sep"></div></div></div>
<p>&nbsp;</p>
<div class="accordian"><h5 class="toggle "><a href="#"><span class="arrow"></span>Linha do Tempo</a></h5><div class="toggle-content " style="">
<p><img class="size-full wp-image-2127 aligncenter" alt="linha do tempo SEBRAE PREVIDÊNCIA" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/linha-do-tempo.jpg" width="886" height="1399" title="SEBRAE PREVIDÊNCIA" /><br />
</div></div>
<p>&nbsp;</p>
<p>A história do SEBRAE PREVIDÊNCIA retrata um sonho: o desejo de um grupo de empregados que buscou soluções para a aposentadoria com a implementação de uma previdência complementar.</p>
<p>A preocupação começou com alguns colaboradores que saíram do Rio de Janeiro e desembarcaram no Sebrae Nacional. Época do Centro Brasileiro de Assistência Gerencial à Pequena Empresa &#8211; Cebrae.</p>
<p>Visitas a instituições para ver como os planos funcionavam eram constantes, além de muitos estudos. A possibilidade de participar de planos de previdência privada, oferecidos por bancos, era uma alternativa sempre avaliada.</p>
<p>Em 1990, o Centro Brasileiro de Assistência Gerencial à Pequena Empresa transformou-se, pelo decreto 99.570, de 9 de outubro, que complementa a Lei 8.029, de 12 de abril, em Serviço Brasileiro de Apoio às Micro e Pequenas Empresas, o Sebrae, que se desvinculava da administração pública transformando-se em serviço social autônomo.</p>
<p>A partir de então, as negociações começaram a tomar novos rumos. Um grupo que fazia parte da Comissão de Relação do Trabalho iniciou uma temporada de discussões a cerca do assunto.</p>
<p>Por alguns anos, esse item constou em quase todas as pautas. Questões burocráticas, investimentos da Instituição e muitos estudos atuariais começaram a ser uma constante na fala dos colaboradores.</p>
<p>A Portaria nº 16, de 2 de fevereiro de 2004, da Secretaria de Previdência Complementar, aprovou a constituição e o funcionamento do Instituto. As primeiras adesões ao Plano SEBRAEPREV aconteceram a partir de dezembro de 2004. Sete unidades estaduais  do Sistema Sebrae tinham buscado soluções independentes a respeito da contratação de um plano de previdência. Depois de muito empenho para adequar caso a caso, todas essas unidades aderiram ao Plano.</p>
<p>Em maio de 2007, a Instituição ganha sede exclusiva e estrutura a equipe de profissionais, o que possibilitou avanços na área de atendimento aos Participantes. São novos passos do Plano SEBRAEPREV com o propósito de consolidar seus instrumentos de governança. Nesse ano foi desenvolvido um programa de visitas às Patrocinadoras, o que possibilitou compreender a importância de um atendimento personalizado.</p>
<p>Mais um ano, mais desafios e mais conquistas. Chega 2008. O ano exigiu da direção do SEBRAE PREVIDÊNCIA permanente atenção aos investimentos e administração em decorrência da crise do mercado financeiro. A Entidade fica entre as 20 instituições de previdência complementar do país que se destacaram nos quesitos governança corporativa e custo administrativo por Participante.</p>
<p>O ano de 2009 foi marcado por mudanças no Regulamento do Plano, pela revisão geral e atualização de cadastros, além da implantação do programa de empréstimo. As estratégias definidas combinaram investimentos e resultados que possibilitaram aumentar a rentabilidade.</p>
<p>O Plano SEBRAEPREV está em todo o Brasil e conta com um grau de adesão de quase 100%. Os colaboradores que iniciam sua carreira, entram no Sebrae com a tranquilidade de optar por um plano de previdência complementar.</p>
<p>A credibilidade da gestão é atestada com os números alcançados. Nossos Participantes, divididos entre as 30 Patrocinadoras, compreendem mais de 4.900 pessoas, sendo 62 Assistidos, dados esses até o junho de 2010. O desafio segue e o próximo objetivo é estar mais próximo do Participante, Representantes e Patrocinadoras imprimindo mais transparência e agilidade nas informações.</p>
<p><b>É fácil constatar o crescente desempenho do SEBRAE PREVIDÊNCIA. Fruto de uma administração qualificada que se prepara para gerir outros planos. Por todas as conquistas e desafios superados desde a sua criação, a história narrada até agora é apenas o início de futuras concretizações com o propósito de oferecer aos Participantes maior segurança e estabilidade.</b></p>
</div>
<div id="tab3" class="tab tab_content">
<img alt="seta azul SEBRAE PREVIDÊNCIA" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/seta-azul.png" width="22" height="44" title="SEBRAE PREVIDÊNCIA" /> <div class="title"><h2>Estrutura de Governança</h2><div class="title-sep-container"><div class="title-sep"></div></div></div>
<p>&nbsp;</p>
<div class="two_third">
<p>As entidades fechadas de previdência complementar (EFPCs), como o SEBRAE PREVIDÊNCIA, bem como empresas em geral, vem adotando códigos de relacionamento e práticas de gestão e prestação de contas, com o objetivo principal de tornar a gestão mais transparente aos participantes, acionistas, cotistas ou outros detentores de direitos dentro da organização. Estes códigos e práticas estão consubstanciados no que se chama hoje de “governança corporativa”.</p>
<p>No SEBRAE PREVIDÊNCIA, a governança corporativa é elemento presente na gestão, contando com a seguinte estrutura:</p>
<p><b>Assembleia Geral</b></p>
<p>As Patrocinadoras com convênio de adesão firmado com o SEBRAE PREVIDÊNCIA reúnem-se em Assembléia de patrocinadores, competindo-lhes eleger os membros do Conselho Deliberativo e os do Conselho Fiscal e seus respectivos suplentes.</p>
<p><b>Conselho Deliberativo</b></p>
<p>É o órgão responsável pela deliberação e orientação superior, ao qual incumbe fixar as diretrizes e políticas do SEBRAE PREVIDÊNCIA, por meio de decisões colegiadas. É composto por oito membros titulares e seus respectivos suplentes.</p>
<p><b>Conselho Fiscal</b></p>
<p>O Conselho Fiscal é o órgão de fiscalização da gestão do SEBRAE PREVIDÊNCIA, sendo composto por quatro membros efetivos e seus respectivos suplentes, todos eleitos pelas Patrocinadoras dentre os participantes dos planos de benefícios.</p>
<p><b>Diretoria Executiva</b></p>
<p>A Diretoria Executiva é o órgão de administração geral do SEBRAE PREVIDÊNCIA, cabendo-lhe cumprir as deliberações do Conselho Deliberativo. É composta por três membros.</p>
</div>
<div class="one_third last">
<p style="text-align: center;"><a href="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/organograma.png"  target="_blank"><img class="aligncenter size-full wp-image-2034" alt="organograma governanca SEBRAE PREVIDÊNCIA" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/organograma_governanca.png" width="296" height="183" title="SEBRAE PREVIDÊNCIA" /></a></div><div class="clearboth"></div>
</div>
<div id="tab4" class="tab tab_content">
<img alt="seta azul SEBRAE PREVIDÊNCIA" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/seta-azul.png" width="22" height="44" title="SEBRAE PREVIDÊNCIA" /> <div class="title"><h2>Nossa Equipe</h2><div class="title-sep-container"><div class="title-sep"></div></div></div>
<p>&nbsp;</p>
<div class="accordian"><h5 class="toggle active"><a href="#"><span class="arrow"></span>Conselho Deliberativo</a></h5><div class="toggle-content default-open" style="display: block;">
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/evandronascimento.jpg" alt="evandronascimento SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Evandro Santos Nascimento</span><span class="person-title">Presidente - NA</span></div><div class="clear"></div></div><div class="person-content"></div></div></div>evandro@sebrae.com.br</div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/jose_neto.jpg" alt="jose neto SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Jose Ferreira de Melo Neto</span><span class="person-title">Titular - RN</span></div><div class="clear"></div></div><div class="person-content"></div></div></div>zecam@rn.sebrae.com.br</div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/maristela.jpg" alt="maristela SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Maristela de Oliveira França</span><span class="person-title">Titular - MS</span></div><div class="clear"></div></div><div class="person-content"></div></div></div>maristela.franca@ms.sebrae.com.br</div>
<div class="one_fourth last"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/gava.jpg" alt="gava SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">José Gava Neto</span><span class="person-title">Titular - PR</span></div><div class="clear"></div></div><div class="person-content"></div></div></div>jgava@pr.sebrae.com.br</div><div class="clearboth"></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/airton.jpg" alt="airton SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Airton Gonçalves Junior</span><span class="person-title">Titular - CE</span></div><div class="clear"></div></div><div class="person-content">airton@ce.sebrae.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/manoel.jpg" alt="manoel SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Manoel Antonio Vieira A.</span><span class="person-title">Titular - AB</span></div><div class="clear"></div></div><div class="person-content">manoel.alexandre.adv@terra.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/andre.jpg" alt="andre SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">André Luis da Silva Dantas</span><span class="person-title">Titular - NA</span></div><div class="clear"></div></div><div class="person-content">andre.dantas@sebrae.com.br</div></div></div></div>
<div class="one_fourth last"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/niltonbarbosa.jpg" alt="niltonbarbosa SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Nilton de Castro Barbosa</span><span class="person-title">Titular - SP</span></div><div class="clear"></div></div><div class="person-content"></div></div></div>niltonb@sebraesp.com.br</div><div class="clearboth"></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/carlossilva.jpg" alt="carlossilva SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Carlos Alberto da Silva</span><span class="person-title">Suplente - NA</span></div><div class="clear"></div></div><div class="person-content"></div></div></div>c.silva@sebrae.com.br</div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/leide.jpg" alt="leide SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Leide Garcia N. Katayama</span><span class="person-title">Suplente - MT</span></div><div class="clear"></div></div><div class="person-content">leide.katayama@mt.sebrae.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/mario.jpg" alt="mario SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Mário José Lacerda de Melo</span><span class="person-title">Suplente - PI</span></div><div class="clear"></div></div><div class="person-content">mario.lacerda@pi.sebrae.com.br</div></div></div></div>
<div class="one_fourth last"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/mariacristina.jpg" alt="mariacristina SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Maria Cristina de A. Souza</span><span class="person-title">Suplente - RR</span></div><div class="clear"></div></div><div class="person-content">cristina@rr.sebrae.com.br</div></div></div></div><div class="clearboth"></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/carloscarreirao.jpg" alt="carloscarreirao SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Carlos Armando Carreirão</span><span class="person-title">Suplente - SC</span></div><div class="clear"></div></div><div class="person-content"></div></div></div>carreirao@sc.sebrae.com.br</div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/elizandra.jpg" alt="elizandra SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Elizandra Litaiff Leonardo</span><span class="person-title">Suplente - AM</span></div><div class="clear"></div></div><div class="person-content">elizandra@am.sebrae.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/clarice.jpg" alt="clarice SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Clarice Maria Veras</span><span class="person-title">Suplente - NA</span></div><div class="clear"></div></div><div class="person-content">clarice.veras@sebrae.com.br</div></div></div></div>
<div class="one_fourth last"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/luizantonio.jpg" alt="luizantonio SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Luiz Antônio Rolim de Moura</span><span class="person-title">Suplente - PR</span></div><div class="clear"></div></div><div class="person-content"></div></div></div>lmoura@pr.sebrae.com.br</div><div class="clearboth"></div>
<p></div><h5 class="toggle "><a href="#"><span class="arrow"></span>Conselho Fiscal</a></h5><div class="toggle-content " style="">
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/tereza.jpg" alt="tereza SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Tereza Fátima de A. Krauz</span><span class="person-title">Titular - MS</span></div><div class="clear"></div></div><div class="person-content">tereza.krauz@ms.sebrae.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/alessandro.jpg" alt="alessandro SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Alessandro Flávio B. Chaves</span><span class="person-title">Titular - MG</span></div><div class="clear"></div></div><div class="person-content"></div></div></div>alessandro.chaves@sebraemg.com.br</div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/vitor.jpg" alt="vitor SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Vitor Roberto Tioqueta</span><span class="person-title">Titular - PR</span></div><div class="clear"></div></div><div class="person-content">vtioqueta@sebraepr.com.br</div></div></div></div>
<div class="one_fourth last"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/robervalgomes1.jpg" alt="robervalgomes1 SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">José Roberval da S. Gomes</span><span class="person-title">Titular - AL</span></div><div class="clear"></div></div><div class="person-content">robervalcabral@al.sebrae.com.br</div></div></div></div><div class="clearboth"></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/alexandre.jpg" alt="alexandre SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Alexandre Rodrigues Alves</span><span class="person-title">Suplente - PE</span></div><div class="clear"></div></div><div class="person-content"></div></div></div>alexandrer@pe.sebrae.com.br</div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/rogerio.jpg" alt="rogerio SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Rogério Amadel Moreira</span><span class="person-title">Suplente - RJ</span></div><div class="clear"></div></div><div class="person-content"></div></div></div>rmoreira@rj.sebrae.com.br</div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/evandropecanha.jpg" alt="evandropecanha SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Evandro Peçanha Alves</span><span class="person-title">Suplente - RJ</span></div><div class="clear"></div></div><div class="person-content"></div></div></div>epecanha@rj.sebrae.com.br</div>
<div class="one_fourth last"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/waldeir1.jpg" alt="waldeir1 SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Waldeir Garcia Ribeiro</span><span class="person-title">Suplente - AP</span></div><div class="clear"></div></div><div class="person-content"></div></div></div>waldeir@ap.sebrae.com.br</div><div class="clearboth"></div>
<p></div><h5 class="toggle "><a href="#"><span class="arrow"></span>Diretoria Executiva</a></h5><div class="toggle-content " style="">
<div class="one_third"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/edjair.jpg" alt="edjair SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Edjair de Sirqueira Alves</span><span class="person-title">Diretor Presidente</span></div><div class="clear"></div></div><div class="person-content">edjair@sebraeprev.com.br</div></div></div></div>
<div class="one_third"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/george.jpg" alt="george SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">George Alberto Carvalhes G Mota</span><span class="person-title">Diretor de Adm e Investimento</span></div><div class="clear"></div></div><div class="person-content">george@sebraeprev.com.br</div></div></div></div>
<div class="one_third last"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/nilton.jpg" alt="nilton SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Nilton Cesar da Silva</span><span class="person-title">Diretor de Seguridade</span></div><div class="clear"></div></div><div class="person-content">nilton@sebraeprev.com.br</div></div></div></div><div class="clearboth"></div>
<p></div><h5 class="toggle "><a href="#"><span class="arrow"></span>Equipe Técnica</a></h5><div class="toggle-content " style="">
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/arthus.jpg" alt="arthus SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Arthus Benazio</span><span class="person-title">Assistente - Cadastro e Arrecadação</span></div><div class="clear"></div></div><div class="person-content">arthus@sebraeprev.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/dilaine.jpg" alt="dilaine SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Dilaine Andrade</span><span class="person-title">Analista - Administrativo e Financeiro (Empréstimo)</span></div><div class="clear"></div></div><div class="person-content">dilaine@sebraeprev.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/luciana2.jpg" alt="luciana2 SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Luciana Cristina Braga</span><span class="person-title">Assistente - GRP e<br />
Assistente de Seguridade - Benefício e Cadastro</span></div><div class="clear"></div></div><div class="person-content">atendimento@sebraeprev.com.br<br />
l.cristina@sebraeprev.com.br</div></div></div></div>
<div class="one_fourth last"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/luciana.jpg" alt="luciana SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Luciana Ribeiro</span><span class="person-title">Gerente - Gerência de Relacionamento com o Participante (GRP)</span></div><div class="clear"></div></div><div class="person-content">luciana@sebraeprev.com.br</div></div></div></div><div class="clearboth"></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/mafra.jpg" alt="mafra SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Mafra Correia Cabral</span><span class="person-title">Assistente</span></div><div class="clear"></div></div><div class="person-content">mafra@sebraeprev.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/maria.jpg" alt="maria SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Maria Catarina Marçal</span><span class="person-title">Técnica - GRP </span></div><div class="clear"></div></div><div class="person-content">catarina@sebraeprev.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/vanessa.jpg" alt="vanessa SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Vanessa Leal</span><span class="person-title">Técnica - Contabilidade</span></div><div class="clear"></div></div><div class="person-content">vanessa@sebraeprev.com.br</div></div></div></div>
<div class="one_fourth last"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/victor.jpg" alt="victor SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Victor Moreira</span><span class="person-title">Analista - Cadastro e Arrecadação</span></div><div class="clear"></div></div><div class="person-content">victor@sebraeprev.com.br</div></div></div></div><div class="clearboth"></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/viviane.jpg" alt="viviane SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Viviane Araújo</span><span class="person-title">Analista - Comunicação</span></div><div class="clear"></div></div><div class="person-content">viviane@sebraeprev.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/kalel.jpg" alt="kalel SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Kalel Alves</span><span class="person-title">Estagiário - Comunicação</span></div><div class="clear"></div></div><div class="person-content">kalel@sebraeprev.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/leandro.jpg" alt="leandro SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Leandro Muniz</span><span class="person-title">Assistente - Seguridade</span></div><div class="clear"></div></div><div class="person-content">leandro@sebraeprev.com.br</div></div></div></div>
<div class="one_fourth last"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/pedro.jpg" alt="pedro SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Pedro Henrique de Oliveira</span><span class="person-title">Estagiário</span></div><div class="clear"></div></div><div class="person-content">pedro@sebraeprev.com.br</div></div></div></div><div class="clearboth"></div></div>
<h5 class="toggle "><a href="#"><span class="arrow"></span>Gestores do Plano</a></h5><div class="toggle-content " style="">
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/mulher.jpg" alt="mulher SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Elsa Maria de Melo</span><span class="person-title">ABASE</span></div><div class="clear"></div></div><div class="person-content">elsamelo@terra.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/mulher.jpg" alt="mulher SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Blenda Agnes N. Belo</span><span class="person-title">ABASE</span></div><div class="clear"></div></div><div class="person-content"></div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/AC-Lívia-Nunes-de-Freitas-Maia-AC.jpg" alt="AC Lívia Nunes de Freitas Maia AC SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Livia Nunes de Freitas Maia</span><span class="person-title">SEBRAE - AC</span></div><div class="clear"></div></div><div class="person-content">livia.freitas@ac.sebrae.com.br</div></div></div></div>
<div class="one_fourth last"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/homem.jpg" alt="homem SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Fabio Silva de Oliveira</span><span class="person-title">SEBRAE - AC</span></div><div class="clear"></div></div><div class="person-content">fabio.oliveira@ac.sebrae.com.br</div></div></div></div><div class="clearboth"></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/AL-Eliane-Miranda-Gonçalves-AL.jpg" alt="AL Eliane Miranda Gonçalves AL SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Eliane Miranda Gonçalves</span><span class="person-title">SEBRAE - AL</span></div><div class="clear"></div></div><div class="person-content">eliane@al.sebrae.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/AL-Lavínia-Peixoto-Barros-Navarro-AL.jpg" alt="AL Lavínia Peixoto Barros Navarro AL SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Lavínia Peixoto Barros Navarro</span><span class="person-title">SEBRAE - AL</span></div><div class="clear"></div></div><div class="person-content">lavinia@al.sebrae.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/homem.jpg" alt="homem SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Marcelo José de Souza</span><span class="person-title">SEBRAE - AM</span></div><div class="clear"></div></div><div class="person-content">marcelos@am.sebrae.com.br</div></div></div></div>
<div class="one_fourth last"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/mulher.jpg" alt="mulher SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">---</span><span class="person-title">SEBRAE - AM</span></div><div class="clear"></div></div><div class="person-content"></div></div></div>&#8212;</div><div class="clearboth"></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/mulher.jpg" alt="mulher SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Keila Almeida</span><span class="person-title">SEBRAE - AP</span></div><div class="clear"></div></div><div class="person-content">keila@ap.sebrae.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/homem.jpg" alt="homem SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Eliel de Paula Dias</span><span class="person-title">SEBRAE - AP</span></div><div class="clear"></div></div><div class="person-content">eliel@ap.sebrae.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/BA-Francisco-Bastos-BA.jpg" alt="BA Francisco Bastos BA SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Francisco Jose C. B. Neto</span><span class="person-title">SEBRAE - BA</span></div><div class="clear"></div></div><div class="person-content">francisco.bastos@ba.sebrae.com.br</div></div></div></div>
<div class="one_fourth last"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/BA-Ana-Paula-Barreto-BA.jpg" alt="BA Ana Paula Barreto BA SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Ana Paula Sampaio Barretto</span><span class="person-title">SEBRAE - BA</span></div><div class="clear"></div></div><div class="person-content"></div></div></div></div><div class="clearboth"></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/CE-Jose-Armistrong-Martins-Cunha-CE.jpg" alt="CE Jose Armistrong Martins Cunha CE SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">José Armistrong Martins Cunha</span><span class="person-title">SEBRAE - CE</span></div><div class="clear"></div></div><div class="person-content">armistrong@ce.sebrae.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/CE-Francisca-Emanuela-Fontenele-CE.jpg" alt="CE Francisca Emanuela Fontenele CE SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Francisca Emanuela Fontenele</span><span class="person-title">SEBRAE - CE</span></div><div class="clear"></div></div><div class="person-content"></div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/DF-Abadia-Luiz-de-Sousa-DF.jpg" alt="DF Abadia Luiz de Sousa DF SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Abadia Luiz de Sousa</span><span class="person-title">SEBRAE - DF</span></div><div class="clear"></div></div><div class="person-content">abadia@df.sebrae.com.br</div></div></div></div>
<div class="one_fourth last"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/DF-Roberta-Labanca-Oliveira-Marques-DF.jpg" alt="DF Roberta Labanca Oliveira Marques DF SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Roberta L. Oliveira Marques</span><span class="person-title">SEBRAE - DF</span></div><div class="clear"></div></div><div class="person-content">roberta.marques@df.sebrae.com.br</div></div></div>
</div><div class="clearboth"></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/Aline-Ferreira-da-Silva-ES_alterada.jpg" alt="Aline Ferreira da Silva ES alterada SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Aline Ferreira da Silva M. Gomes</span><span class="person-title">SEBRAE - ES</span></div><div class="clear"></div></div><div class="person-content">aline.gomes@es.sebrae.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/mulher.jpg" alt="mulher SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Rowena Ribeiro Cavatti</span><span class="person-title">SEBRAE - ES</span></div><div class="clear"></div></div><div class="person-content">rowena.cavatti@es.sebrae.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/GO-Gilka-de-Freitas-GO.jpg" alt="GO Gilka de Freitas GO SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Gilka de Freitas</span><span class="person-title">SEBRAE - GO</span></div><div class="clear"></div></div><div class="person-content">gilka@sebraego.com.br</div></div></div></div>
<div class="one_fourth last"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/mulher.jpg" alt="mulher SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Edna Maria da Silva Martins Uto</span><span class="person-title">SEBRAE - GO</span></div><div class="clear"></div></div><div class="person-content">edna@sebraego.com.br</div></div></div></div><div class="clearboth"></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/mulher.jpg" alt="mulher SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Carmen Neiva Carvalho Gondim</span><span class="person-title">SEBRAE - GO</span></div><div class="clear"></div></div><div class="person-content">carmen.gondim@sebraego.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/MA-Cleonilce-Prazeres-MA.jpg" alt="MA Cleonilce Prazeres MA SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Cleonilce Costa Santos</span><span class="person-title">SEBRAE - MA</span></div><div class="clear"></div></div><div class="person-content">cleonilce@ma.sebrae.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/MA-Maria-José-Costa-Dias-Diniz-MA.jpg" alt="MA Maria José Costa Dias Diniz MA SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Maria José Costa Dias Diniz</span><span class="person-title">SEBRAE - MA</span></div><div class="clear"></div></div><div class="person-content">zeze@ma.sebrae.com.br</div></div></div></div>
<div class="one_fourth last"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/MG-Maurício-Martins-da-Paixão-MG.jpg" alt="MG Maurício Martins da Paixão MG SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Maurício Martins da Paixão</span><span class="person-title">SEBRAE - MG</span></div><div class="clear"></div></div><div class="person-content">mauricio.paixao@sebraemg.com.br</div></div></div></div><div class="clearboth"></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/mulher.jpg" alt="mulher SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Cristina Vasconcelos Mesquita</span><span class="person-title">SEBRAE - MG</span></div><div class="clear"></div></div><div class="person-content">cristina.mesquita@sebraemg.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/MS-Adriana-Maria-Mattas-Campos-MS.jpg" alt="MS Adriana Maria Mattas Campos MS SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Adriana Maria Mattas Campos</span><span class="person-title">SEBRAE - MS</span></div><div class="clear"></div></div><div class="person-content">adriana.campos@ms.sebrae.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/mulher.jpg" alt="mulher SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Camilla Sousa</span><span class="person-title">SEBRAE - MS</span></div><div class="clear"></div></div><div class="person-content">camilla.sousa@ms.sebrae.com.br</div></div></div></div>
<div class="one_fourth last"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/mulher.jpg" alt="mulher SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Suleima M. Coelho</span><span class="person-title">SEBRAE - MT</span></div><div class="clear"></div></div><div class="person-content">suleima.coelho@mt.sebrae.com.br</div></div></div></div><div class="clearboth"></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/Zoca-Farias-da-Costa-MT.jpg" alt="Zoca Farias da Costa MT SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Zoca Farias da Costa</span><span class="person-title">SEBRAE - MT</span></div><div class="clear"></div></div><div class="person-content">zoca.costa@mt.sebrae.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/NA-Gilberto-Guimarães-da-Silva-NA.jpg" alt="NA Gilberto Guimarães da Silva NA SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Gilberto Guimarães da Silva</span><span class="person-title">SEBRAE Nacional</span></div><div class="clear"></div></div><div class="person-content">gilberto.silva@sebrae.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/homem.jpg" alt="homem SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Sérgio José S. Figliero</span><span class="person-title">SEBRAE Nacional</span></div><div class="clear"></div></div><div class="person-content">sergiofigliero@sebrae.com.br</div></div></div></div>
<div class="one_fourth last"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/mulher.jpg" alt="mulher SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Fabricia Siqueira Correa</span><span class="person-title">SEBRAE - PA</span></div><div class="clear"></div></div><div class="person-content">fabricia@pa.sebrae.com.br</div></div></div></div><div class="clearboth"></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/homem.jpg" alt="homem SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">José Carlos da Silva Monteiro</span><span class="person-title">SEBRAE - PA</span></div><div class="clear"></div></div><div class="person-content">josecarlos@pa.sebrae.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/PB-Eduardo-Colaço-de-Sousa-PB.jpg" alt="PB Eduardo Colaço de Sousa PB SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Eduardo Colaço de Sousa</span><span class="person-title">SEBRAE - PB</span></div><div class="clear"></div></div><div class="person-content">eduardo@pb.sebrae.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/mulher.jpg" alt="mulher SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Maria de Jesus Verissímo Leite</span><span class="person-title">SEBRAE - PB</span></div><div class="clear"></div></div><div class="person-content">gel@sebraepb.com.br</div></div></div></div>
<div class="one_fourth last"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/PE-Virginia-Siqueira-Nogueira-Nunes-PE.jpg" alt="PE Virginia Siqueira Nogueira Nunes PE SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Virginia Siqueira Nogueira Nunes</span><span class="person-title">SEBRAE - PE</span></div><div class="clear"></div></div><div class="person-content">virginias@pe.sebrae.com.br</div></div></div>
</div><div class="clearboth"></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/PE-Veronica-Maria-Campos-Gomes-PE.jpg" alt="PE Veronica Maria Campos Gomes PE SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Veronica Maria Campos Gomes da Silva</span><span class="person-title">SEBRAE - PE</span></div><div class="clear"></div></div><div class="person-content">veronicac@pe.sebrae.com.br</div></div></div>
</div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/eva.png" alt="eva SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Eva Pereira de Moura</span><span class="person-title">SEBRAE - PI</span></div><div class="clear"></div></div><div class="person-content">eva@pi.sebrae.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/val.jpg" alt="val SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Valéria Moraes de Sousa Ribeiro</span><span class="person-title">SEBRAE - PI</span></div><div class="clear"></div></div><div class="person-content">vmoraes@pi.sebrae.com.br</div></div></div></div>
<div class="one_fourth last"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/PR-Alba-Silva-Anastácio-Soares-PR.jpg" alt="PR Alba Silva Anastácio Soares PR SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Alba Silva Anastácio Soares</span><span class="person-title">SEBRAE - PR</span></div><div class="clear"></div></div><div class="person-content">asoares@pr.sebrae.com.br</div></div></div></div><div class="clearboth"></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/PR-Renata-Mauricio-Fonseca-PR.jpg" alt="PR Renata Mauricio Fonseca PR SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Renata Fonseca</span><span class="person-title">SEBRAE - PR</span></div><div class="clear"></div></div><div class="person-content">rfonseca@pr.sebrae.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/mulher.jpg" alt="mulher SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Márcia Bontorim</span><span class="person-title">SEBRAE - RJ</span></div><div class="clear"></div></div><div class="person-content">mbontorim@sebraerj.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/Rute-Lima-RJ_alterada.jpg" alt="Rute Lima RJ alterada SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Rute Lima</span><span class="person-title">SEBRAE - RJ</span></div><div class="clear"></div></div><div class="person-content">rute@sebraerj.com.br</div></div></div></div>
<div class="one_fourth last"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/RN-Ana-Cristina-Coelho-Pinheiro-RN.jpg" alt="RN Ana Cristina Coelho Pinheiro RN SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Ana Cristina Coelho Pinheiro</span><span class="person-title">SEBRAE - RN</span></div><div class="clear"></div></div><div class="person-content">cristina@rn.sebrae.com.br</div></div></div></div><div class="clearboth"></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/mulher.jpg" alt="mulher SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Maria Lúcia Carvalho</span><span class="person-title">SEBRAE - RN</span></div><div class="clear"></div></div><div class="person-content">luciacarvalho@rn.sebrae.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/RO-Deise-Mara-Rosa-de-Lima-RO.jpg" alt="RO Deise Mara Rosa de Lima RO SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Deise Mara Rosa de Lima</span><span class="person-title">SEBRAE - RO</span></div><div class="clear"></div></div><div class="person-content">deise@ro.sebrae.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/RO-Carlos-Alberto-Machado-de-França-RO.jpg" alt="RO Carlos Alberto Machado de França RO SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Carlos Alberto Machado de França</span><span class="person-title">SEBRAE - RO</span></div><div class="clear"></div></div><div class="person-content">machado@ro.sebrae.com.br</div></div></div></div>
<div class="one_fourth last"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/RR-Maria-de-Jesus-Sousa-de-Oliveira-RR.jpg" alt="RR Maria de Jesus Sousa de Oliveira RR SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Maria de Jesus de Sousa Oliveira</span><span class="person-title">SEBRAE - RR</span></div><div class="clear"></div></div><div class="person-content">maria.oliveira@rr.sebrae.com.br</div></div></div></div><div class="clearboth"></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/RR-Elsie-Maria-Gorete-Nascimento-RR.jpg" alt="RR Elsie Maria Gorete Nascimento RR SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Elsie Maria Gorete Nascimento da Silva</span><span class="person-title">SEBRAE - RR</span></div><div class="clear"></div></div><div class="person-content">elsie.silva@rr.sebrae.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/RR-Noelea-da-Silva-Sousa-RR.jpg" alt="RR Noelea da Silva Sousa RR SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Noelea da Silva Sousa</span><span class="person-title">SEBRAE - RR</span></div><div class="clear"></div></div><div class="person-content">noelea.sousa@rr.sebrae.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/RS-Luiz-Ávila-RS.jpg" alt="RS Luiz Ávila RS SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Luiz Ávila</span><span class="person-title">SEBRAE - RS</span></div><div class="clear"></div></div><div class="person-content">luizavila@sebrae-rs.com.br</div></div></div></div>
<div class="one_fourth last"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/RS-Luciano-Amaral-Ramos-RS.jpg" alt="RS Luciano Amaral Ramos RS SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Luciano Amaral Ramos</span><span class="person-title">SEBRAE - RS</span></div><div class="clear"></div></div><div class="person-content">lucianor@sebrae-rs.com.br</div></div></div></div><div class="clearboth"></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/SC-Eliane-da-Rosa-Figueira-Costa-SC.jpg" alt="SC Eliane da Rosa Figueira Costa SC SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Eliane da Rosa Figueira Costa</span><span class="person-title">SEBRAE - SC</span></div><div class="clear"></div></div><div class="person-content">eliane@sc.sebrae.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/SC-Claudio-Augusto-Nienkoetter-SC.jpg" alt="SC Claudio Augusto Nienkoetter SC SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Claudio Augusto Nienkoetter</span><span class="person-title">SEBRAE - SC</span></div><div class="clear"></div></div><div class="person-content">claudion@sc.sebrae.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/SE-Marleide-Santos-de-Oliveira-SE.jpg" alt="SE Marleide Santos de Oliveira SE SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Marleide Santos de Oliveira</span><span class="person-title">SEBRAE - SE</span></div><div class="clear"></div></div><div class="person-content">marleide.oliveira@se.sebrae.com.br</div></div></div></div>
<div class="one_fourth last"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/Erathosthenes-..jpg" alt="Erathosthenes . SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Erathosthenes Menezes Junior</span><span class="person-title">SEBRAE - SE</span></div><div class="clear"></div></div><div class="person-content">junior.menezes@se.sebrae.com.br</div></div></div></div><div class="clearboth"></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/SP-Isaíra-Rosiene-Beserra-Batista-SP.jpg" alt="SP Isaíra Rosiene Beserra Batista SP SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Isaíra Rosiene Beserra Batista </span><span class="person-title">SEBRAE - SP</span></div><div class="clear"></div></div><div class="person-content">isairarbb@sebraesp.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/SP-Patrícia-Silva-Borba-SP.jpg" alt="SP Patrícia Silva Borba SP SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Patricia Silva Borba</span><span class="person-title">SEBRAE - SP</span></div><div class="clear"></div></div><div class="person-content">patriciasb@sebraesp.com.br</div></div></div></div>
<div class="one_fourth"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/TO-Walbênia-Lemos-da-S.-Torres-TO.jpg" alt="TO Walbênia Lemos da S. Torres TO SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Walbenia Lemos da S. Torres</span><span class="person-title">SEBRAE - TO</span></div><div class="clear"></div></div><div class="person-content"></div></div></div></div>
<div class="one_fourth last"><div class="person"><img class="person-img" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/TO-Joseane-Rodrigues-Leite-TO.jpg" alt="TO Joseane Rodrigues Leite TO SEBRAE PREVIDÊNCIA"  title="SEBRAE PREVIDÊNCIA" /><div class="person-desc"><div class="person-author clearfix"><div class="person-author-wrapper"><span class="person-name">Joseane Rodrigues Leite</span><span class="person-title">SEBRAE - TO</span></div><div class="clear"></div></div><div class="person-content">joseane.leite@to.sebrae.com.br</div></div></div></div><div class="clearboth"></div>
<p></div></div>
</div>
<div id="tab5" class="tab tab_content">
<img alt="seta azul SEBRAE PREVIDÊNCIA" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/seta-azul.png" width="22" height="44" title="SEBRAE PREVIDÊNCIA" /> <div class="title"><h2>Documentos Institucionais</h2><div class="title-sep-container"><div class="title-sep"></div></div></div>
<p>&nbsp;</p>
<div class="one_fourth">
<p style="text-align: center;"><a href="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/Mapa-Estrategico-fin.pdf" onclick="javascript:_gaq.push(['_trackEvent','download','http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/Mapa-Estrategico-fin.pdf']);" target="_blank"><img class="aligncenter size-full wp-image-2030" alt="planejamento estrategico SEBRAE PREVIDÊNCIA" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/09/planejamento_estrategico.png" width="296" height="183" title="SEBRAE PREVIDÊNCIA" /></a></p>
</div>
<div class="one_fourth">
<p style="text-align: center;"><a href="http://sebraeprevidencia.com.br/wp-content/uploads/2014/12/ESTATUTO-APROVA%C3%87%C3%83O-DEFINITIVA-PREVIC.pdf" onclick="javascript:_gaq.push(['_trackEvent','download','http://sebraeprevidencia.com.br/wp-content/uploads/2014/12/ESTATUTO-APROVA%C3%87%C3%83O-DEFINITIVA-PREVIC.pdf']);" target="_blank"><img class="aligncenter size-full wp-image-2028" alt="estatuto SEBRAE PREVIDÊNCIA" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/09/estatuto.png" width="296" height="183" title="SEBRAE PREVIDÊNCIA" /></a></p>
</div>
<div class="one_fourth">
<p style="text-align: center;"><a href="http://sebraeprevidencia.com.br/wp-content/uploads/2013/11/CodEtica.pdf" onclick="javascript:_gaq.push(['_trackEvent','download','http://sebraeprevidencia.com.br/wp-content/uploads/2013/11/CodEtica.pdf']);" target="_blank"><img class="aligncenter size-full wp-image-2026" alt="codigo etica SEBRAE PREVIDÊNCIA" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/09/codigo_etica.png" width="296" height="183" title="SEBRAE PREVIDÊNCIA" /></a></p>
</div>
<div class="one_fourth last">
<p style="text-align: center;"><a href="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/Coletânea-de-normas-2013.pdf" onclick="javascript:_gaq.push(['_trackEvent','download','http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/Coletânea-de-normas-2013.pdf']);" target="_blank"><img class="aligncenter size-full wp-image-2027" alt="coletanea normas SEBRAE PREVIDÊNCIA" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/09/coletanea_normas.png" width="296" height="183" title="SEBRAE PREVIDÊNCIA" /></a></p>
</div><div class="clearboth"></div>
<div class="one_fourth">
<p style="text-align: center;"><a href="http://sebraeprevidencia.com.br/wp-content/uploads/2013/11/GoverCorp.pdf" onclick="javascript:_gaq.push(['_trackEvent','download','http://sebraeprevidencia.com.br/wp-content/uploads/2013/11/GoverCorp.pdf']);" target="_blank"><img class="aligncenter size-full wp-image-2029" alt="governanca corporativa SEBRAE PREVIDÊNCIA" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/09/governanca_corporativa.png" width="296" height="183" title="SEBRAE PREVIDÊNCIA" /></a></p>
</div>
<div class="one_fourth">
<p style="text-align: center;"><a href="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/Politica_Relacionamento.pdf" onclick="javascript:_gaq.push(['_trackEvent','download','http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/Politica_Relacionamento.pdf']);"><img class="aligncenter size-full wp-image-6343" alt="politica relacionamento SEBRAE PREVIDÊNCIA" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/politica_relacionamento.png" width="296" height="183" title="SEBRAE PREVIDÊNCIA" /></a></p>
</div>
<div class="one_fourth">
<p style="text-align: left;"><a href="http://sebraeprevidencia.com.br/wp-content/uploads/2013/11/Regulamento.pdf" onclick="javascript:_gaq.push(['_trackEvent','download','http://sebraeprevidencia.com.br/wp-content/uploads/2013/11/Regulamento.pdf']);" target="_blank"><img class="aligncenter" alt="regulamento sebraeprev SEBRAE PREVIDÊNCIA" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/09/regulamento_sebraeprev.png" width="296" height="183" title="SEBRAE PREVIDÊNCIA" /></a></p>
</div>
<div class="one_fourth last">
<p><a href="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/pesaquisa_satisfacao_2013_04_30.pdf" onclick="javascript:_gaq.push(['_trackEvent','download','http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/pesaquisa_satisfacao_2013_04_30.pdf']);"><img class="aligncenter size-full wp-image-6340" alt="pesquisa satisfacao1 SEBRAE PREVIDÊNCIA" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/pesquisa_satisfacao1.png" width="296" height="183" title="SEBRAE PREVIDÊNCIA" /></a><br />
</div><div class="clearboth"></div>
<div class="one_fourth">
<p><a href="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/2ª-Pesquisa-de-Satisfação.pdf" onclick="javascript:_gaq.push(['_trackEvent','download','http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/2ª-Pesquisa-de-Satisfação.pdf']);"><img class="aligncenter size-full wp-image-6341" alt="pesquisa satisfacao2 SEBRAE PREVIDÊNCIA" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/pesquisa_satisfacao2.png" width="296" height="183" title="SEBRAE PREVIDÊNCIA" /></a></p>
</div>
<div class="one_fourth">
<p style="text-align: center;"><a href="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/DEMONSTRAÇÃO-ATUARIAL-2014.pdf" onclick="javascript:_gaq.push(['_trackEvent','download','http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/DEMONSTRAÇÃO-ATUARIAL-2014.pdf']);"><img class="aligncenter size-full wp-image-6493" alt="demos atuariais2014 SEBRAE PREVIDÊNCIA" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/demos_atuariais2014.png" width="296" height="183" title="SEBRAE PREVIDÊNCIA" /></a></p>
</div>
<div class="one_fourth">
<p style="text-align: left;"><a href="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/demos_atuariais_2013.pdf" onclick="javascript:_gaq.push(['_trackEvent','download','http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/demos_atuariais_2013.pdf']);" target="_blank"><img class="aligncenter" alt="demos atuariais2013 SEBRAE PREVIDÊNCIA" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/demos_atuariais2013.png" width="296" height="183" title="SEBRAE PREVIDÊNCIA" /></a></p>
</div>
<div class="one_fourth last">
<p style="text-align: center;"><a href="http://sebraeprevidencia.com.br/wp-content/uploads/2013/11/DRAA2012.pdf" onclick="javascript:_gaq.push(['_trackEvent','download','http://sebraeprevidencia.com.br/wp-content/uploads/2013/11/DRAA2012.pdf']);" target="_blank"><img alt="demos atuariais2012 SEBRAE PREVIDÊNCIA" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/demos_atuariais2012.png" width="296" height="183" title="SEBRAE PREVIDÊNCIA" /></a></p>
</div><div class="clearboth"></div>
<div class="one_fourth">
<p style="text-align: center;"><a href="http://sebraeprevidencia.com.br/wp-content/uploads/2013/11/DRAA2011.pdf" onclick="javascript:_gaq.push(['_trackEvent','download','http://sebraeprevidencia.com.br/wp-content/uploads/2013/11/DRAA2011.pdf']);" target="_blank"><img alt="demos atuariais2011 SEBRAE PREVIDÊNCIA" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/demos_atuariais2011.png" width="296" height="183" title="SEBRAE PREVIDÊNCIA" /></a></p>
</div>
<div class="one_fourth last">
<p><a href="http://sebraeprevidencia.com.br/wp-content/uploads/2013/11/DRAA2010.pdf" onclick="javascript:_gaq.push(['_trackEvent','download','http://sebraeprevidencia.com.br/wp-content/uploads/2013/11/DRAA2010.pdf']);" target="_blank"><img class="aligncenter" alt="demos atuariais2010 SEBRAE PREVIDÊNCIA" src="http://sebraeprevidencia.com.br/wp-content/uploads/2013/07/demos_atuariais2010.png" width="296" height="183" title="SEBRAE PREVIDÊNCIA" /></a></p>
</div><div class="clearboth"></div>
<p></div></div></div></div>
							</div>
					</div>
			</div>
	<div id="sidebar" style="display:none">		<div id="recent-posts-2" class="widget widget_recent_entries">		<div class="heading"><h3>Outras Notícias</h3></div>		<ul>
					<li>
				<a href="http://sebraeprevidencia.com.br/comissoes-tematicas-sao-definidas-pelo-conselho-deliberativo/" title="Comissões Temáticas são definidas pelo Conselho Deliberativo">Comissões Temáticas são definidas pelo Conselho Deliberativo</a>
							<span class="post-date">14 de maio de 2015</span>
						</li>
					<li>
				<a href="http://sebraeprevidencia.com.br/iv-forum-sebraeprev-de-economia/" title="IV Fórum SEBRAEPREV de economia">IV Fórum SEBRAEPREV de economia</a>
							<span class="post-date">14 de maio de 2015</span>
						</li>
					<li>
				<a href="http://sebraeprevidencia.com.br/informe-sebraeprev-de-abril-confira/" title="Informe SEBRAEPREV de Abril: confira!">Informe SEBRAEPREV de Abril: confira!</a>
							<span class="post-date">12 de maio de 2015</span>
						</li>
					<li>
				<a href="http://sebraeprevidencia.com.br/perfil-de-investimento-e-do-percentual-de-contribuicao-alteracao-de-junho-ate-3107/" title="Período para alterar o perfil de investimento e o percentual de contribuição começa em junho e vai até o dia 31 de julho">Período para alterar o perfil de investimento e o percentual de contribuição começa em junho e vai até o dia 31 de julho</a>
							<span class="post-date">11 de maio de 2015</span>
						</li>
					<li>
				<a href="http://sebraeprevidencia.com.br/conselhos-promovem-reunioes/" title="Conselhos promovem reuniões">Conselhos promovem reuniões</a>
							<span class="post-date">4 de maio de 2015</span>
						</li>
				</ul>
		</div></div>
		</div>
          
	</div>
<?php get_footer();?>